# Welcome to Jekyll!
#

# Site settings
title: Salamah & Ridzwan
description: Salamah & Ridzwan are getting married on 12.08.2017!
owner: Your Name # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
section:
  bride & groom: "#about"
  our story: "#our-story"
  memories: "#memories"
  photo album: "#photo-album"
  event: "#event"
  rsvp: "#rsvp"
social:
  facebook-official: https://facebook.com/satuhearty
  twitter: https://twitter.com/satuhearty
  instagram: https://instagram.com/satuhearty
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
